// src/pages/api/contact.ts
// Handles general contact form submissions.
// DO NOT edit this file per client — update src/lib/email.config.ts instead.

import type { APIRoute } from 'astro';
import { Resend } from 'resend';
import mailchimp from '@mailchimp/mailchimp_marketing';
import { EMAIL_CONFIG } from '~/lib/email.config';
import { sendWithAlert, notifySubmission, fieldsFromFormData } from '~/lib/form-alert';

const resend = new Resend(import.meta.env.RESEND_API_KEY);
// Slack destination. FORM_SLACK_WEBHOOK is this client's own channel and takes
// precedence for BOTH submissions and failures; FORM_ALERT_SLACK_URL is the
// shared fallback for clients without a channel of their own.
const SLACK_WEBHOOK =
  import.meta.env.FORM_SLACK_WEBHOOK || import.meta.env.FORM_ALERT_SLACK_URL;

if (EMAIL_CONFIG.mailchimp.enabled) {
  mailchimp.setConfig({
    apiKey: import.meta.env.MAILCHIMP_API_KEY,
    server: import.meta.env.MAILCHIMP_SERVER_PREFIX,
  });
}

export const POST: APIRoute = async ({ request }) => {
  try {
    const data   = await request.formData();

    // Honeypot: bots fill hidden fields, humans don't
    if (data.get('website')?.toString()) {
      return new Response(JSON.stringify({ success: true }), { status: 200 });
    }

    const name    = data.get('name')?.toString().trim()    ?? '';
    const email   = data.get('email')?.toString().trim()   ?? '';
    const message = data.get('message')?.toString().trim() ?? '';
    const subscribe = data.get('subscribe') === 'true';
    const source  = data.get('source')?.toString().trim()  ?? '';

    if (!email || !name || !message) {
      return new Response(JSON.stringify({ error: 'All fields are required.' }), { status: 400 });
    }

    // Internal notification
    let notified = true;
    try {
      await sendWithAlert(
        {
          client: EMAIL_CONFIG.brand.name,
          formName: 'Contact form',
          slackWebhookUrl: SLACK_WEBHOOK,
          alertEmail: { apiKey: import.meta.env.RESEND_API_KEY, to: EMAIL_CONFIG.alertsTo, from: EMAIL_CONFIG.from.notifications },
        },
        () => resend.emails.send({
        from: EMAIL_CONFIG.from.notifications,
        to: EMAIL_CONFIG.notify,
        subject: `New contact form: ${name}`,
        html: `
          <h2>New Contact Form Submission</h2>
          <p><strong>Name:</strong> ${name}</p>
          <p><strong>Email:</strong> ${email}</p>
          <p><strong>Message:</strong></p>
          <p>${message.replace(/\n/g, '<br>')}</p>
          <p><strong>Newsletter opt-in:</strong> ${subscribe ? 'Yes' : 'No'}</p>
          ${source ? `<hr><p style="color:#888;font-size:13px"><strong>Source</strong><br>${source.replace(/\n/g, '<br>')}</p>` : ''}
        `,
        }),
      );
    } catch (err) {
      notified = false;
      console.error('Resend notify error:', err);
    }

    // Log the submission to the client's Slack channel. It posts even when the
    // email failed — that message is then the only record of the enquiry.
    await notifySubmission({
      client: EMAIL_CONFIG.brand.name,
      slackWebhookUrl: SLACK_WEBHOOK,
      route: 'Contact form',
      formName: `Contact form → ${[EMAIL_CONFIG.notify].flat().join(', ')}`,
      delivered: notified,
      fields: fieldsFromFormData(data),
    });

    // Confirmation to sender
    try {
      await resend.emails.send({
        from: EMAIL_CONFIG.from.hello,
        to: email,
        subject: EMAIL_CONFIG.copy.contact.confirmSubject,
        html: EMAIL_CONFIG.copy.contact.confirmBody(name, EMAIL_CONFIG.brand.url),
      });
    } catch (err) {
      console.error('Resend confirm error:', err);
    }

    // Optional Mailchimp opt-in
    if (subscribe && EMAIL_CONFIG.mailchimp.enabled) {
      try {
        await mailchimp.lists.addListMember(import.meta.env.MAILCHIMP_AUDIENCE_ID, {
          email_address: email,
          status: 'subscribed',
          merge_fields: { FNAME: name.split(' ')[0] },
          tags: EMAIL_CONFIG.mailchimp.defaultTags,
        });
      } catch (err: any) {
        console.error('Mailchimp opt-in error:', err?.response?.body ?? err);
      }
    }

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error('Contact API error:', err);
    return new Response(JSON.stringify({ error: 'Something went wrong. Please try again.' }), { status: 500 });
  }
};
