// src/pages/api/subscribe.ts
// Handles newsletter/email list opt-ins (email only, name optional).
// DO NOT edit this file per client — update src/lib/email.config.ts instead.

import type { APIRoute } from 'astro';
import mailchimp from '@mailchimp/mailchimp_marketing';
import { Resend } from 'resend';
import { EMAIL_CONFIG } from '~/lib/email.config';
import { notifySubmission, fieldsFromFormData } from '~/lib/form-alert';

const resend = new Resend(import.meta.env.RESEND_API_KEY);
// Slack destination. FORM_SLACK_WEBHOOK is this client's own channel and takes
// precedence for BOTH submissions and failures; FORM_ALERT_SLACK_URL is the
// shared fallback for clients without a channel of their own.
const SLACK_WEBHOOK =
  import.meta.env.FORM_SLACK_WEBHOOK || import.meta.env.FORM_ALERT_SLACK_URL;

if (EMAIL_CONFIG.mailchimp.enabled) {
  mailchimp.setConfig({
    apiKey: import.meta.env.MAILCHIMP_API_KEY,
    server: import.meta.env.MAILCHIMP_SERVER_PREFIX,
  });
}

export const POST: APIRoute = async ({ request }) => {
  try {
    const data      = await request.formData();

    // Honeypot: bots fill hidden fields, humans don't
    if (data.get('website')?.toString()) {
      return new Response(JSON.stringify({ success: true }), { status: 200 });
    }

    const email     = data.get('email')?.toString().trim()     ?? '';
    const firstName = data.get('firstName')?.toString().trim() ?? '';

    if (!email) {
      return new Response(JSON.stringify({ error: 'Email is required.' }), { status: 400 });
    }

    // Add to Mailchimp (silently pass if already subscribed)
    if (EMAIL_CONFIG.mailchimp.enabled) {
      try {
        await mailchimp.lists.addListMember(import.meta.env.MAILCHIMP_AUDIENCE_ID, {
          email_address: email,
          status: 'subscribed',
          merge_fields: { FNAME: firstName },
          tags: EMAIL_CONFIG.mailchimp.defaultTags,
        });
      } catch (err: any) {
        const alreadyExists = err?.response?.body?.title === 'Member Exists';
        if (!alreadyExists) {
          console.error('Mailchimp subscribe error:', err?.response?.body ?? err);
          // Post it anyway or the address is gone: Mailchimp never took it, and
          // this route emails nobody internally.
          await notifySubmission({
            client: EMAIL_CONFIG.brand.name,
            slackWebhookUrl: SLACK_WEBHOOK,
            route: 'Newsletter sign-up',
            formName: 'Mailchimp rejected the add',
            delivered: false,
            fields: fieldsFromFormData(data),
          });
          return new Response(JSON.stringify({ error: 'Could not subscribe. Please try again.' }), { status: 500 });
        }
      }
    }

    // Log the sign-up to the client's Slack channel. Nobody is emailed
    // internally about a newsletter opt-in, so without this the only trace is a
    // row in a Mailchimp audience.
    await notifySubmission({
      client: EMAIL_CONFIG.brand.name,
      slackWebhookUrl: SLACK_WEBHOOK,
      route: 'Newsletter sign-up',
      formName: EMAIL_CONFIG.mailchimp.enabled ? 'Added to Mailchimp' : 'Mailchimp is off for this client',
      fields: fieldsFromFormData(data),
    });

    // Welcome email
    try {
      await resend.emails.send({
        from: EMAIL_CONFIG.from.hello,
        to: email,
        subject: EMAIL_CONFIG.copy.subscribe.confirmSubject,
        html: EMAIL_CONFIG.copy.subscribe.confirmBody(firstName),
      });
    } catch (err) {
      console.error('Resend welcome error:', err);
    }

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error('Subscribe API error:', err);
    return new Response(JSON.stringify({ error: 'Something went wrong. Please try again.' }), { status: 500 });
  }
};
